---
- name: Enable netconf
  hosts: all
  tasks:
    - name: "Enable NETCONF"
      junos_netconf:
        netconf_port: 830
        state: present
      vars:
        ansible_connection: local
      tags: netconf
