---
- name: Get JunoOS Facts
  hosts: all
  gather_facts: false
  ansible_python_interpreter: /usr/bin/python3
  
  tasks:

  - name: collect default set of facts
    junos_facts:
      gather_subset: all
    
  - name: Print JunOS facts to console
    debug:
      msg: "{{ ansible_facts }}"
